{
 "title": "Spark_Perf_Dashboard_v03_with_annotations",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "UserName",
    "label": "User",
    "query": "SHOW TAG VALUES WITH KEY = \"username\""
   },
   {
    "name": "ApplicationId",
    "label": "Spark Application Id",
    "query": "SHOW TAG VALUES WITH KEY = \"applicationid\" WHERE \"username\" =~ /$UserName/ "
   }
  ]
 },
 "panels": [
  { "title": "Summary metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "N# of Active Tasks - latest value",
   "type": "stat",
   "description": "Latest sample of the value of number of active tasks, summed over all executors active in the selected time filter interval.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "stage.runningStages",
     "query": "select sum(perprocessval) from (SELECT process, last(\"value\") as perprocessval FROM \"threadpool.activeTasks\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Executors CPU time",
   "type": "stat",
   "description": "Total executor CPU time computed from from executor metrics. Displays CPU time used by all the executors' JVMs active in the selected time filter interval. It contains CPU time used for executing tasks and for other activities in the JVM, notably garbage collection. Note, values from executors that are no more active in the selected time window are not accounted for.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jvmCpuTime",
     "query": "select sum(lastvalperprocess) from ( SELECT process, last(value) as lastvalperprocess FROM jvmCpuTime WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Task CPU Usage ",
   "type": "stat",
   "description": "Total task CPU usage from task metrics. Displays CPU time used for all the completed tasks, from the task metrics data source. Note, values from executors that are no more active in the selected time window are not counted.\n",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "job.activeJobs",
     "query": "select sum(lastvalperprocess) from (SELECT process, last(value) as lastvalperprocess FROM \"cpuTime.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Task GC Time ",
   "type": "stat",
   "description": "Total time spent in GC operations during task execution. Displays values for all the completed tasks, from the task metrics data source. Note, values from executors that are no more active in the selected time window are not counted.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "job.activeJobs",
     "query": "select sum(perprocessval) from (SELECT process, last(\"value\") as perprocessval FROM \"jvmGCTime.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "N# of Completed Tasks",
   "type": "stat",
   "description": "Number of completed tasks, from JVM threadpool metrics. Note, values from executors that are no more active in the selected time window are not counted.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "threadpool.completeTasks",
     "query": "select sum(perprocessval) from (SELECT process, last(\"value\") as perprocessval FROM \"threadpool.completeTasks\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Current N# of Running Stages - latest value",
   "type": "stat",
   "description": "Number of running stages from the DAG scheduler.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "stage.failedStages",
     "query": "SELECT \"value\" FROM \"stage.runningStages\" WHERE (\"applicationid\" =~ /^$ApplicationId$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap memory Used (% of maximum usable)",
   "type": "gauge",
   "description": "Latest value of the % of heap memory used, averaging over executors and driver. JVM metric from MemoryMXBean. Conditional to spark.metrics.conf.*.source.jvm.class=org.apache.spark.metrics.source.JvmSource",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heap.usage",
     "query": "select mean(lastvalperprocess)*100 from  (SELECT process, last(value) as lastvalperprocess FROM \"heap.usage\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Cumulative HDFS Bytes Read",
   "type": "stat",
   "description": "Bytes read from HDFS. Note, values from executors that are no more active in the selected time window are not counted.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "job.activeJobs",
     "query": "select sum(lastvalperprocess) from (SELECT process, last(value) as lastvalperprocess  FROM \"filesystem.hdfs.read_bytes\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Cumulative HDFS Bytes Written",
   "type": "stat",
   "description": "Bytes written to HDFS. Note, values from executors that are no more active in the selected time window are not counted.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "job.activeJobs",
     "query": "select sum(lastvalperprocess) from (SELECT process, last(value) as lastvalperprocess  FROM \"filesystem.hdfs.write_bytes\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Succeeded Jobs Count",
   "type": "stat",
   "description": "Number of succeeded jobs, from the appStatus metric (introduced in Spark 3.0). Conditional to spark.metrics.appStatusSource.enabled=true (default is false)",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jobs.succeededJobs.count",
     "query": "SELECT value FROM \"jobs.succeededJobs.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "N# of Failed Tasks",
   "type": "stat",
   "description": "Failed tasks for the appStatus metrics. Conditional to spark.metrics.appStatusSource.enabled=true (default is false)",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "tasks.completedTasks.count",
     "query": "SELECT \"value\" FROM \"tasks.failedTasks.count\" WHERE (\"applicationid\" =~ /^$ApplicationId$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Failed Stages",
   "type": "stat",
   "description": "Number of failed stages from the appStatus \n metrics.\nConditional to a configuration parameter:\nspark.metrics.appStatusSource.enabled=true (default is false)",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "stage.failedStages",
     "query": "SELECT \"value\" FROM \"stages.failedStages.count\" WHERE (\"applicationid\" =~ /^$ApplicationId$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  { "title": "Spark workload metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Number of Active Tasks",
   "type": "graph",
   "description": "Number of active tasks per executor.\n",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "N# Active Tasks" }
   ],
   "targets": [
    {
     "alias": "N# active tasks - Executor $tag_process",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"threadpool.activeTasks\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Executors JVM CPU Utilization (N# cores-equivalent)",
   "type": "graph",
   "description": "Total executor CPU utilization computed from executors' JVM instrumentation. The value is normalized in \"N# of core equivalent\", that is the number of cores running at 100% that would give an equivalent value of CPU utilization.\n",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    {
     "format": "short",
     "label": "CPU Utilization (N# cores equivalent)"
    }
   ],
   "targets": [
    {
     "alias": "JVM CPU - Executor $tag_process",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "jvmCpuTime",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  / 1000000000 FROM \"jvmCpuTime\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Time (N# of cores equivalent) - from task metrics",
   "type": "graph",
   "description": "Time the JVM process has spent in garbage collection. The value is normalized in \"N# of core equivalent\", that is the hypothetical number of cores working at 100% on GC that would give an equivalent result.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "GC Time (N# cores equivalent)" }
   ],
   "targets": [
    {
     "alias": "GCTime - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "jvmGCTime.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  / 1000 FROM  \"jvmGCTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval),process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Task CPU Utilization (N# cores equivalent) -  from Task metrics",
   "type": "graph",
   "description": "Total task CPU utilization computed from task metrics. The value is normalized in \"N# of core equivalent\", that is the number of cores running at 100% that would give an equivalent value of CPU utilization.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    {
     "format": "short",
     "label": "CPU Utilization (N# cores equivalent)"
    }
   ],
   "targets": [
    {
     "alias": "Task CPU - Executor $tag_process",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "cpuTime.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  / 1000000000 FROM \"cpuTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Executor run time and wait time components",
   "type": "graph",
   "description": "Executor run time and wait time components compared. The run time spent by Spark executors is aggregated per area of activity. The difference between tun time measuremets and wait time measuremts can be interpreted as due to time not instrumented (e.g. HDFS/filesystem I/O wait time). The values are normalized in \"N# of core equivalent\", that is the number of cores running at 100% that would yield an equivalent value for the given metric.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    {
     "format": "none",
     "label": "Time component (N# cores equivalent)"
    }
   ],
   "targets": [
    {
     "alias": "deserializeCpuTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "deserializeCpuTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000000000 as perprocessval FROM \"deserializeCpuTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "deserializeTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "deserializeTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000 as perprocessval FROM \"deserializeTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "cpuTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cpuTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000000000 as perprocessval FROM \"cpuTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "shuffleWriteTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "shuffleWriteTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000000000 as perprocessval FROM \"shuffleWriteTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "resultSerializationTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "resultSerializationTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000 as perprocessval FROM \"resultSerializationTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "shuffleFetchWaitTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "shuffleFetchWaitTime.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000 as perprocessval FROM \"shuffleFetchWaitTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "jvmGCTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000 as perprocessval FROM \"jvmGCTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "runTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) / 1000 as perprocessval FROM \"runTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executor Run Time - from task metrics",
   "type": "graph",
   "description": "Time the Executor has spent running tasks, including idle time and wait time (for I/O or other event). The value is normalized in \"N# of core equivalent\", that is the hypothetical number of cores working at 100% running tasks that would give an equivalent result.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    {
     "format": "none",
     "label": "Task Run Time (N# cores equivalent)"
    }
   ],
   "targets": [
    {
     "alias": "run time - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "shuffleFetchWaitTime.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s) / 1000  FROM \"runTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of completed tasks per executor.",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "N# of completed tasks" }
   ],
   "targets": [
    {
     "alias": "Executor $tag_process",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "threadpool.completeTasks",
     "query": "SELECT last(\"value\") FROM \"threadpool.completeTasks\" WHERE (\"applicationid\" =~ /^$ApplicationId$/) AND $timeFilter GROUP BY \"process\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Write Time - from task metrics",
   "type": "graph",
   "description": "Time the Executor has spent writing shuffle data. The value is normalized in \"N# of core equivalent\", that is the hypothetical number of cores working at 100% on shuffle writing that would give an equivalent result.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    {
     "format": "none",
     "label": "Shuffle Write Time (N# cores equivalent)"
    }
   ],
   "targets": [
    {
     "alias": "shuffle write time - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "shuffleFetchWaitTime.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s) / 1000000000  FROM \"shuffleWriteTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Block Manager: memory and disk used",
   "type": "graph",
   "description": "Storage memory and disk used by the block manager.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    {
     "format": "decmbytes",
     "label": "Block manager memory and disk used"
    }
   ],
   "targets": [
    {
     "alias": "Heap Memory  Used - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "heap.used",
     "query": "SELECT mean(value) FROM \"memory.onHeapMemUsed_MB\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" },
      { "condition": "AND", "key": "process", "operator": "!=", "value": "driver" }
     ]
    },
    {
     "alias": "Non-heap Memory  Used - Executor $tag_process",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(value) FROM \"memory.offHeapMemUsed_MB\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Disk used - Executor $tag_process",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(value) FROM \"disk.diskSpaceUsed_MB\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spark Executors Memory Metrics (Spark 3.0)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 }
  },
  {
   "title": "JVM On Heap Memory",
   "type": "graph",
   "description": "JVM Heap Memory",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "decbytes", "label": "JVM Heap Memory" }
   ],
   "targets": [
    {
     "alias": "JVM heap memory - Executor $tag_process",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"JVMHeapMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Off Heap Memory",
   "type": "graph",
   "description": "JVM Off Heap Memory",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "decbytes", "label": "JVM Off Heap Memory" }
   ],
   "targets": [
    {
     "alias": "JVM off heap memory - Executor $tag_process",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"JVMOffHeapMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "OnHeapUnifiedMemory",
   "type": "graph",
   "description": "OnHeapUnifiedMemory",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "decbytes", "label": "OnHeapUnifiedMemory" }
   ],
   "targets": [
    {
     "alias": "OnHeapUnifiedMemory - Executor $tag_process",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"OnHeapUnifiedMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "OffHeapUnifiedMemory",
   "type": "graph",
   "description": "OffHeapUnifiedMemory",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "decbytes", "label": "OffHeapUnifiedMemory" }
   ],
   "targets": [
    {
     "alias": "OffHeapUnifiedMemory - Executor $tag_process",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"OffHeapUnifiedMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "OnHeap Execution Memory",
   "type": "graph",
   "description": "OnHeapExecutionMemory",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "decbytes", "label": "OnHeap Execution Memory" }
   ],
   "targets": [
    {
     "alias": "OnHeapExecutionMemory - Executor $tag_process",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"OnHeapExecutionMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "OnHeap Storage Memory",
   "type": "graph",
   "description": "OnHeap Storage Memory",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "decbytes", "label": "OnHeap Storage Memory" }
   ],
   "targets": [
    {
     "alias": "OnHeapStorageMemory - Executor $tag_process",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"OnHeapStorageMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "MinorGCTime",
   "type": "graph",
   "description": "MinorGCTime",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    {
     "format": "none",
     "label": "MinorGCTime (normalized in core equivalent)"
    }
   ],
   "targets": [
    {
     "alias": "GCTime - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "jvmGCTime.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  / 1000 FROM  \"MinorGCTime\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "MajorGCTime",
   "type": "graph",
   "description": "MajorGCTime",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    {
     "format": "none",
     "label": "MajorGCTime (normalized in core equivalent)"
    }
   ],
   "targets": [
    {
     "alias": "GCTime - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "jvmGCTime.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  / 1000 FROM  \"MajorGCTime\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "ProcessTreeJVMRSSMemory",
   "type": "graph",
   "description": "ProcessTreeJVMRSSMemory. Conditional to spark.executor.processTreeMetrics.enabled=true",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "decbytes", "label": "ProcessTreeJVMRSSMemory" }
   ],
   "targets": [
    {
     "alias": "JMV RSS - Executor $tag_process",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"ProcessTreeJVMRSSMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "ProcessTreePythonRSSMemory",
   "type": "graph",
   "description": "ProcessTreePythonRSSMemory. Conditional to spark.executor.processTreeMetrics.enabled=true",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "decbytes", "label": "ProcessTreeJVMRSSMemory" }
   ],
   "targets": [
    {
     "alias": "Python RSS - Executor $tag_process",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threadpool.activeTasks",
     "query": "SELECT mean(value) FROM \"ProcessTreePythonRSSMemory\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM source  memory metrics (conditional to spark.metrics.conf.*.source.jvm.class=org.apache.spark.metrics.source.JvmSource)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 }
  },
  {
   "title": "Executor JVM Total Memory Used",
   "type": "graph",
   "description": "Total memory (heap + non-heap) used per executor.  From MemoryMXBean.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "bytes", "label": "JVM total memory used" }
   ],
   "targets": [
    {
     "alias": "Total Memory  Used - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "heap.used",
     "query": "SELECT mean(value) FROM \"total.used\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter AND process != 'driver'  GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" },
      { "condition": "AND", "key": "process", "operator": "!=", "value": "driver" }
     ]
    }
   ]
  },
  {
   "title": "Executor JVM Heap Memory Used",
   "type": "graph",
   "description": "Heap memory used per executor.  From MemoryMXBean.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "bytes", "label": "JVM heap memory used" }
   ],
   "targets": [
    {
     "alias": "Heap Memory  Used - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "heap.used",
     "query": "SELECT mean(value) FROM \"heap.used\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter AND process != 'driver' GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" },
      { "condition": "AND", "key": "process", "operator": "!=", "value": "driver" }
     ]
    }
   ]
  },
  {
   "title": "Driver JVM Total Memory Used",
   "type": "graph",
   "description": "Total memory (heap + non-heap) used by the driver.  From MemoryMXBean.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "bytes", "label": "JVM total memory used" }
   ],
   "targets": [
    {
     "alias": "Total Memory  Used - $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "heap.used",
     "query": "SELECT mean(value) FROM \"total.used\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter AND process = 'driver' GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" },
      { "condition": "AND", "key": "process", "operator": "!=", "value": "driver" }
     ]
    }
   ]
  },
  { "title": "Spark I/O metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 } },
  {
   "title": "HDFS bytes read/sec",
   "type": "graph",
   "description": "HDFS read throughput.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "Bps", "label": "HDFS bytes read/sec" }
   ],
   "targets": [
    {
     "alias": "hdfs bytes read - Executor $tag_process",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "filesystem.hdfs.read_bytes",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  FROM \"filesystem.hdfs.read_bytes\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "HDFS bytes written/sec",
   "type": "graph",
   "description": "HDFS write throughput.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 150 },
   "yaxes": [
    { "format": "Bps", "label": "HDFS bytes written/sec" }
   ],
   "targets": [
    {
     "alias": "hdfs bytes read - Executor $tag_process",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "filesystem.hdfs.read_bytes",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  FROM \"filesystem.hdfs.write_bytes\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Total Bytes Read/sec - from task metrics",
   "type": "graph",
   "description": "Shuffle read throughput.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "Bps", "label": "Shuffle total bytes read/sec" }
   ],
   "targets": [
    {
     "alias": "shuffle Total Bytes Read - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "shuffleTotalBytesRead.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  FROM \"shuffleTotalBytesRead.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Bytes Written/sec - from taskmetrics",
   "type": "graph",
   "description": "Shuffle write throughput.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "Bps", "label": "Shuffle bytes written/sec" }
   ],
   "targets": [
    {
     "alias": "shuffleBytesWritten - Executor $tag_process",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "shuffleBytesWritten.count",
     "query": "SELECT non_negative_derivative(mean(value), 1s)  FROM \"shuffleBytesWritten.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY  time($__interval), process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Read Composition",
   "type": "graph",
   "description": "Details of shuffle I/O operations, local and remote.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 171 },
   "yaxes": [
    { "format": "Bps", "label": "Shuffle bytes read/sec" }
   ],
   "targets": [
    {
     "alias": "shuffleRemoteBytesRead",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "shuffleRemoteBytesRead.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) as perprocessval FROM \"shuffleRemoteBytesRead.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval), process) GROUP BY time($__interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    },
    {
     "alias": "shuffleLocalBytesRead",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "shuffleLocalBytesRead.count",
     "query": "select sum(perprocessval) from (SELECT non_negative_derivative(last(\"value\"), 1s) as perprocessval FROM \"shuffleLocalBytesRead.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY time($__interval),  \"process\") GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  }
 ]
}