#!/bin/bash
set -Eeuo pipefail

umask 027

GRAFANA_CONFIG="${GRAFANA_CONFIG:-/etc/grafana/grafana.ini}"
GRAFANA_HOME="${GRAFANA_HOME:-/usr/share/grafana}"
GRAFANA_DATA="${GRAFANA_DATA:-/var/lib/grafana}"
GRAFANA_LOGS="${GRAFANA_LOGS:-/var/log/grafana}"
GRAFANA_PLUGINS="${GRAFANA_PLUGINS:-/var/lib/grafana/plugins}"
GRAFANA_PROVISIONING="${GRAFANA_PROVISIONING:-/etc/grafana/provisioning}"

VM_BIN="${VM_BIN:-/victoria-metrics-prod}"
VM_STORAGE_DATA_PATH="${VM_STORAGE_DATA_PATH:-/victoria-metrics-data}"

GRAFANA_PID=""
TELEGRAF_PID=""
VM_PID=""


log() {
    printf '[spark-dashboard] %s\n' "$*"
}


is_true() {
    case "${1:-}" in
        true|TRUE|yes|YES|1) return 0 ;;
        *)                    return 1 ;;
    esac
}


find_grafana_binary() {
    if command -v grafana >/dev/null 2>&1; then
        command -v grafana
    elif [[ -x /usr/share/grafana/bin/grafana ]]; then
        echo "/usr/share/grafana/bin/grafana"
    else
        echo "Cannot find Grafana executable" >&2
        exit 1
    fi
}


find_telegraf_binary() {
    if command -v telegraf >/dev/null 2>&1; then
        command -v telegraf
    elif [[ -x /usr/bin/telegraf ]]; then
        echo "/usr/bin/telegraf"
    else
        echo "Cannot find Telegraf executable" >&2
        exit 1
    fi
}


run_as_user() {
    local user="$1"
    shift

    if command -v runuser >/dev/null 2>&1; then
        exec runuser -u "${user}" -- "$@"
    else
        # Fallback for very minimal images
        local command_line
        printf -v command_line '%q ' "$@"
        exec su -s /bin/bash "${user}" -c "${command_line}"
    fi
}


prepare_directories() {
    install -d -o grafana -g grafana -m 0750 \
        "${GRAFANA_DATA}" \
        "${GRAFANA_LOGS}" \
        "${GRAFANA_PLUGINS}"

    install -d -m 0755 \
        "${VM_STORAGE_DATA_PATH}"
}


configure_grafana_https() {
    local https_enabled="${GRAFANA_HTTPS_ENABLED:-false}"
    local cert_file="${GRAFANA_CERT_FILE:-/etc/grafana/certs/tls.crt}"
    local cert_key="${GRAFANA_CERT_KEY:-/etc/grafana/certs/tls.key}"
    local root_url="${GRAFANA_ROOT_URL:-}"

    local staged_cert_dir="/run/spark-dashboard/grafana-certs"
    local staged_cert_file="${staged_cert_dir}/tls.crt"
    local staged_cert_key="${staged_cert_dir}/tls.key"

    # Remove configuration generated by an earlier execution.
    sed -i \
        '/^; spark-dashboard HTTPS settings$/,/^; end spark-dashboard HTTPS settings$/d' \
        "${GRAFANA_CONFIG}"

    if ! is_true "${https_enabled}"; then
        return
    fi

    if [[ ! -r "${cert_file}" ]]; then
        echo "Grafana HTTPS certificate is not readable: ${cert_file}" >&2
        ls -la "$(dirname "${cert_file}")" >&2 || true
        exit 1
    fi

    if [[ ! -r "${cert_key}" ]]; then
        echo "Grafana HTTPS private key is not readable: ${cert_key}" >&2
        ls -la "$(dirname "${cert_key}")" >&2 || true
        exit 1
    fi

    install -d -o grafana -g grafana -m 0750 "${staged_cert_dir}"
    install -o grafana -g grafana -m 0644 \
        "${cert_file}" "${staged_cert_file}"
    install -o grafana -g grafana -m 0640 \
        "${cert_key}" "${staged_cert_key}"

    {
        echo
        echo "; spark-dashboard HTTPS settings"
        echo "[server]"
        echo "protocol = https"
        echo "cert_file = ${staged_cert_file}"
        echo "cert_key = ${staged_cert_key}"

        if [[ -n "${root_url}" ]]; then
            echo "root_url = ${root_url}"
        fi

        echo "; end spark-dashboard HTTPS settings"
    } >> "${GRAFANA_CONFIG}"
}


configure_grafana_admin_password() {
    local admin_password="${GRAFANA_ADMIN_PASSWORD:-${GF_SECURITY_ADMIN_PASSWORD:-}}"
    local password_dir="/run/spark-dashboard/grafana-admin"
    local password_file="${password_dir}/admin-password"

    sed -i \
        '/^; spark-dashboard admin password settings$/,/^; end spark-dashboard admin password settings$/d' \
        "${GRAFANA_CONFIG}"

    if [[ -z "${admin_password}" ]]; then
        return
    fi

    install -d -o grafana -g grafana -m 0750 "${password_dir}"

    printf '%s' "${admin_password}" > "${password_file}"
    chown grafana:grafana "${password_file}"
    chmod 0640 "${password_file}"

    {
        echo
        echo "; spark-dashboard admin password settings"
        echo "[security]"
        echo "admin_password = \$__file{${password_file}}"
        echo "; end spark-dashboard admin password settings"
    } >> "${GRAFANA_CONFIG}"
}


wait_for_http() {
    local name="$1"
    local url="$2"
    local pid="$3"
    local insecure="${4:-false}"
    local attempts="${5:-60}"

    local -a curl_args=(-fsS)

    if is_true "${insecure}"; then
        curl_args+=(-k)
    fi

    log "Waiting for ${name}..."

    for ((i = 1; i <= attempts; i++)); do
        if curl "${curl_args[@]}" "${url}" >/dev/null 2>&1; then
            log "${name} is ready"
            return 0
        fi

        if ! kill -0 "${pid}" 2>/dev/null; then
            echo "${name} exited while waiting for readiness" >&2
            return 1
        fi

        sleep 1
    done

    echo "Timed out waiting for ${name}: ${url}" >&2
    return 1
}


start_victoriametrics() {
    if [[ ! -x "${VM_BIN}" ]]; then
        echo "VictoriaMetrics executable not found: ${VM_BIN}" >&2
        exit 1
    fi

    log "Starting VictoriaMetrics"

    "${VM_BIN}" \
        -storageDataPath="${VM_STORAGE_DATA_PATH}" &

    VM_PID=$!

    wait_for_http \
        "VictoriaMetrics" \
        "http://127.0.0.1:8428/health" \
        "${VM_PID}"
}


start_telegraf() {
    local telegraf_bin
    telegraf_bin="$(find_telegraf_binary)"

    log "Starting Telegraf"

    (
        run_as_user telegraf \
            "${telegraf_bin}" \
            --config /etc/telegraf/telegraf.conf
    ) &

    TELEGRAF_PID=$!

    # Telegraf does not necessarily expose an HTTP health endpoint.
    # Give it a moment and make sure it hasn't immediately exited.
    sleep 1

    if ! kill -0 "${TELEGRAF_PID}" 2>/dev/null; then
        echo "Telegraf failed to start" >&2
        wait "${TELEGRAF_PID}" || true
        exit 1
    fi

    log "Telegraf started"
}


start_grafana() {
    local grafana_bin
    grafana_bin="$(find_grafana_binary)"

    log "Starting Grafana"

    (
        run_as_user grafana \
            "${grafana_bin}" server \
            --homepath="${GRAFANA_HOME}" \
            --config="${GRAFANA_CONFIG}" \
            --packaging=deb \
            "cfg:default.paths.data=${GRAFANA_DATA}" \
            "cfg:default.paths.logs=${GRAFANA_LOGS}" \
            "cfg:default.paths.plugins=${GRAFANA_PLUGINS}" \
            "cfg:default.paths.provisioning=${GRAFANA_PROVISIONING}"
    ) &

    GRAFANA_PID=$!

    local protocol="http"
    local insecure="false"

    if is_true "${GRAFANA_HTTPS_ENABLED:-false}"; then
        protocol="https"
        insecure="true"
    fi

    wait_for_http \
        "Grafana" \
        "${protocol}://127.0.0.1:3000/api/health" \
        "${GRAFANA_PID}" \
        "${insecure}" \
        90
}


shutdown() {
    trap - SIGTERM SIGINT EXIT

    log "Stopping services..."

    local pid

    for pid in \
        "${GRAFANA_PID:-}" \
        "${TELEGRAF_PID:-}" \
        "${VM_PID:-}"
    do
        if [[ -n "${pid}" ]] && kill -0 "${pid}" 2>/dev/null; then
            kill -TERM "${pid}" 2>/dev/null || true
        fi
    done

    # Give processes a short opportunity to exit normally.
    for _ in {1..10}; do
        local still_running=false

        for pid in \
            "${GRAFANA_PID:-}" \
            "${TELEGRAF_PID:-}" \
            "${VM_PID:-}"
        do
            if [[ -n "${pid}" ]] && kill -0 "${pid}" 2>/dev/null; then
                still_running=true
            fi
        done

        if [[ "${still_running}" == false ]]; then
            break
        fi

        sleep 1
    done

    # Force anything which ignored SIGTERM.
    for pid in \
        "${GRAFANA_PID:-}" \
        "${TELEGRAF_PID:-}" \
        "${VM_PID:-}"
    do
        if [[ -n "${pid}" ]] && kill -0 "${pid}" 2>/dev/null; then
            kill -KILL "${pid}" 2>/dev/null || true
        fi
    done

    wait 2>/dev/null || true

    log "Services stopped"
}


monitor_services() {
    log "All services started"

    set +e
    wait -n "${GRAFANA_PID}" "${TELEGRAF_PID}" "${VM_PID}"
    local exit_code=$?
    set -e

    echo "A service exited unexpectedly (exit code ${exit_code})" >&2

    shutdown
    exit "${exit_code}"
}


main() {
    trap shutdown SIGTERM SIGINT

    prepare_directories
    configure_grafana_admin_password
    configure_grafana_https

    # Start storage first so Telegraf and Grafana can immediately connect.
    start_victoriametrics
    start_telegraf
    start_grafana

    monitor_services
}


main "$@"

