{
 "title": "Puppet",
 "tags": [ "config" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "rp", "query": "SHOW RETENTION POLICIES" },
   {
    "name": "hostgroup",
    "query": "appserver, database, dia, dir, dbod, hadoop, hadoop_ng, nile"
   }
  ]
 },
 "panels": [
  { "title": "Aggregations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hosts Reporting",
   "type": "singlestat",
   "description": "Number of hosts reporting via CollectD during the selected period of time",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) as Hosts from (select  last(max_value)  from $rp.\"puppet_time\" where value_instance='compiled' and max_value > 0 and toplevel_hostgroup =~ /^$hostgroup/  and time > now() - 90m  group by host)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hosts per Hosgroup",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 3, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) as Hosts from (select  last(max_value), toplevel_hostgroup  as  Hostgroup  from $rp.\"puppet_time\" where value_instance='compiled' and toplevel_hostgroup =~ /^$hostgroup/  and time > now() -90m group by host) group by toplevel_hostgroup",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hosts per environment",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) as Hosts from (select  last(max_value), submitter_environment  as  environment  from $rp.\"puppet_time\" where value_instance='compiled' and toplevel_hostgroup =~ /^$hostgroup/  and time > now() -90m group by host) group by submitter_environment",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hosts with failed Puppet resources",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select  last(\"max_value\"), submitter_environment  as  environment  from $rp.\"puppet_run\" where value_instance='failed' and max_value > 0 and toplevel_hostgroup =~ /^$hostgroup/  and time > now() -1h group by  host, submitter_hostgroup\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Puppet runs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select  last(\"max_value\")*1000 as last_run, submitter_environment  as  environment  from $rp.\"puppet_time\" where value_instance='last_run' and max_value > 0 and toplevel_hostgroup =~ /^$hostgroup/  group by  host, submitter_hostgroup limit 1\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slow Puppet Agent Executions",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max_value as \"Duration\" FROM \"puppet_run\" WHERE (\"toplevel_hostgroup\" =~ /$hostgroup/ and \"value_instance\" = 'time' and max_value > 120 and time > now() -60m) group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Puppet Agent Execution times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "$tag_value_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "puppet_run",
     "query": "SELECT max_value, value_instance FROM \"puppet_run\" WHERE (\"toplevel_hostgroup\" =~ /$hostgroup/ and \"value_instance\" = 'time') and $timeFilter",
     "select": [
      [
       { "params": [ "current_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "toplevel_hostgroup", "operator": "=", "value": "dbod" }
     ]
    }
   ]
  },
  {
   "title": "Config Retrieval",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "alias": "$tag_value_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "puppet_run",
     "query": "SELECT max_value, value_instance FROM \"puppet_run\" WHERE (\"toplevel_hostgroup\" =~ /^$hostgroup/ and \"value_instance\" = 'config_retrieval') and $timeFilter",
     "select": [
      [
       { "params": [ "current_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "toplevel_hostgroup", "operator": "=", "value": "dbod" }
     ]
    }
   ]
  },
  { "title": "Puppet Executions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Successful Compilations per Hostgroup per Environment",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Hosts" }
   ],
   "targets": [
    {
     "alias": "$tag_toplevel_hostgroup $tag_submitter_environment",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"tmp\") from (select  max(\"max_value\")  as  tmp  from $rp.\"puppet_time\" where value_instance='compiled' and toplevel_hostgroup =~ /^$hostgroup/  and $timeFilter group by time(60m),  \"host\"  ) group by time(60m), \"toplevel_hostgroup\", \"submitter_environment\"  fill(none)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average changes per host",
   "type": "graph",
   "description": "Target: 0",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Resources" }
   ],
   "targets": [
    {
     "alias": "$tag_toplevel_hostgroup",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(\"tmp\") from (select  last(\"max_value\")  as  tmp  from $rp.\"puppet_run\" where value_instance='changed' and toplevel_hostgroup =~ /^$hostgroup/  and $timeFilter group by time(60m),  \"host\"  ) group by time(60m), \"toplevel_hostgroup\"  fill(none)\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Resources per Hostgroup",
   "type": "graph",
   "description": "Target: 0",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Resources" }
   ],
   "targets": [
    {
     "alias": "$tag_toplevel_hostgroup",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"tmp\") from (select  last(\"max_value\")  as  tmp  from $rp.\"puppet_run\" where value_instance='failed' and toplevel_hostgroup =~ /^$hostgroup/  and $timeFilter group by time(60m),  \"host\"  ) group by time(60m), \"toplevel_hostgroup\" fill(none)\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Resources per Environment",
   "type": "graph",
   "description": "Target: 0",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Resources" }
   ],
   "targets": [
    {
     "alias": "$tag_submitter_environment",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"tmp\") from (select  last(\"max_value\")  as  tmp  from $rp.\"puppet_run\" where value_instance='failed' and toplevel_hostgroup =~ /^$hostgroup/  and $timeFilter group by time(60m),  \"host\"  ) group by time(60m), \"submitter_environment\"  fill(none)\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Restarted Resources per Hostgroup",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "Resources" }
   ],
   "targets": [
    {
     "alias": "$tag_toplevel_hostgroup - Restarted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"tmp\") from (select  last(\"max_value\")  as  tmp  from $rp.\"puppet_run\" where value_instance='restarted' and toplevel_hostgroup =~ /^$hostgroup/  and $timeFilter group by time(60m),  \"host\"  ) group by time(6m), \"toplevel_hostgroup\"  fill(none)\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_toplevel_hostgroup - Restart Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"tmp\") from (select  last(\"max_value\")  as  tmp  from $rp.\"puppet_run\" where value_instance='restart_failed' and toplevel_hostgroup =~ /^$hostgroup/  and $timeFilter group by time(60m),  \"host\"  ) group by time(6m), \"toplevel_hostgroup\"  fill(none)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}